services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - fyt

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - fyt
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fyt

networks:
    fyt:
      driver: bridge
  
volumes:
  mongodb_data:
    driver: local
  